In [64]:
from pprint import pprint
import sympy as sp
from sympy import Matrix
import numpy as np

# ejercicio 2x2

In [65]:
print('\n ------------- Exercise 8 ------------- \n')

augmented_A = sp.Matrix([[-0.8, 0.7, 0],[0.8, -0.7, 0]])

print('The augmented matrix (A|b):')
pprint(augmented_A)
A_new = augmented_A.rref()[0]
print('The row echelon form of the matrix is:')
pprint(A_new)


 ------------- Exercise 8 ------------- 

The augmented matrix (A|b):
Matrix([
[-0.8,  0.7, 0],
[ 0.8, -0.7, 0]])
The row echelon form of the matrix is:
Matrix([
[1, -0.875, 0],
[0,      0, 0]])


# ejercicio 3x3

In [66]:
print('\n ------------- Exercise 4 ------------- \n')

augmented_A = sp.Matrix([[2, -3, 1, -1],[1, -2, 2, -3], [3, 1, -1, 9]])

print('The augmented matrix (A|b):')
pprint(augmented_A)
A_new = augmented_A.rref()[0]
print('The row echelon form of the matrix is:')
pprint(A_new)


 ------------- Exercise 4 ------------- 

The augmented matrix (A|b):
Matrix([
[2, -3,  1, -1],
[1, -2,  2, -3],
[3,  1, -1,  9]])
The row echelon form of the matrix is:
Matrix([
[1, 0, 0,   15/7],
[0, 1, 0,  19/14],
[0, 0, 1, -17/14]])


In [67]:
print('\n ------------- Exercise 5 ------------- \n')

augmented_A = sp.Matrix([[1, -1, 4, -5],[3, 0, 1, 0], [-1, 1, -4, 20]])

print('The augmented matrix (A|b):')
pprint(augmented_A)
A_new = augmented_A.rref()[0]
print('The row echelon form of the matrix is:')
pprint(A_new)


 ------------- Exercise 5 ------------- 

The augmented matrix (A|b):
Matrix([
[ 1, -1,  4, -5],
[ 3,  0,  1,  0],
[-1,  1, -4, 20]])
The row echelon form of the matrix is:
Matrix([
[1, 0,   1/3, 0],
[0, 1, -11/3, 0],
[0, 0,     0, 1]])


In [68]:
print('\n ------------- Exercise 6 ------------- \n')

augmented_A = sp.Matrix([[-1, 1, 2, 0],[1, 2, 1, 6], [-2, -1, 1, -6]])

print('The augmented matrix (A|b):')
pprint(augmented_A)
A_new = augmented_A.rref()[0]
print('The row echelon form of the matrix is:')
pprint(A_new)


 ------------- Exercise 6 ------------- 

The augmented matrix (A|b):
Matrix([
[-1,  1, 2,  0],
[ 1,  2, 1,  6],
[-2, -1, 1, -6]])
The row echelon form of the matrix is:
Matrix([
[1, 0, -1, 2],
[0, 1,  1, 2],
[0, 0,  0, 0]])


In [69]:
print('\n ------------- Exercise 7 ------------- \n')

augmented_A = sp.Matrix([[-0.6, 0.2, 0.2, 0],[0.1, -0.3, 0.2, 0], [0.5, 0.1, -0.4, 0]])

print('The augmented matrix (A|b):')
pprint(augmented_A)
A_new = augmented_A.rref()[0]
print('The row echelon form of the matrix is:')
pprint(A_new)


 ------------- Exercise 7 ------------- 

The augmented matrix (A|b):
Matrix([
[-0.6,  0.2,  0.2, 0],
[ 0.1, -0.3,  0.2, 0],
[ 0.5,  0.1, -0.4, 0]])
The row echelon form of the matrix is:
Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0]])


## Ejercicio 1 (única solución)

In [70]:
# Exercise 1
print('\n ------------- Exercise 1 ------------- \n')

augmented_A = sp.Matrix([[3, -2, 4],[5, 2, 12]])

print('The augmented matrix (A|b):')
pprint(augmented_A)
A_new = augmented_A.rref()[0]
print('The row echelon form of the matrix is:')
pprint(A_new)



 ------------- Exercise 1 ------------- 

The augmented matrix (A|b):
Matrix([
[3, -2,  4],
[5,  2, 12]])
The row echelon form of the matrix is:
Matrix([
[1, 0, 2],
[0, 1, 1]])


In [71]:
A = np.array([[3, -2], [5, 2]])
print('\n Coefficient matrix A: \n')
pprint(A)

print('\n Column vector of constant terms b:\n')
b = np.array([[4], [12]])
pprint(b)

detA = np.linalg.det(A)
print('\n Determinant of matrix:', detA)

if detA == 0:
    print("The system of linear equations has no solution or infinitely many solutions.")
else: 
    print("The system of linear equations has exactly one solution:")
    u = np.linalg.solve(A,b)
    print(u)



 Coefficient matrix A: 

array([[ 3, -2],
       [ 5,  2]])

 Column vector of constant terms b:

array([[ 4],
       [12]])

 Determinant of matrix: 15.999999999999998
The system of linear equations has exactly one solution:
[[2.]
 [1.]]


In [72]:
print("La matriz augmented_A es de tamaño", augmented_A.shape)
print("La matriz A es de tamaño", A.shape)
print("La matriz b es de tamaño", b.shape)

La matriz augmented_A es de tamaño (2, 3)
La matriz A es de tamaño (2, 2)
La matriz b es de tamaño (2, 1)


In [73]:
print('Número de columnas de A:', A.shape[1])
print('Número de filas de b:', b.shape[0])

if A.shape[1]==b.shape[0]:
    print("El SEL está bien definido")
else:
    print("El SEL NO está bien definido")

Número de columnas de A: 2
Número de filas de b: 2
El SEL está bien definido


## Ejercicio 2 (infinitas soluciones)

In [74]:
########################### Exercise 2
print('\n ------------- Exercise 2 ------------- \n')

augmented_A = sp.Matrix([[1, -1, 7],[2, -2, 14]])

print('The augmented matrix (A|b):')
pprint(augmented_A)
A_new = augmented_A.rref()[0]
print('The row echelon form of the matrix is:')
pprint(A_new)

A = np.array([[1, -1], [2, -2]])
print('\n Coefficient matrix A: \n')
pprint(A)

print('\n Column vector of constant terms b:\n')
b = np.array([7, 14])
print(b)

detA = np.linalg.det(A)
print('\n Determinant of matrix:', detA)

if detA == 0:
    print("The system of linear equations has no solution or infinitely many solutions.")
else: 
    print("The system of linear equations has exactly one solution:")
    u = np.linalg.solve(A,b)
    print(u)



 ------------- Exercise 2 ------------- 

The augmented matrix (A|b):
Matrix([
[1, -1,  7],
[2, -2, 14]])
The row echelon form of the matrix is:
Matrix([
[1, -1, 7],
[0,  0, 0]])

 Coefficient matrix A: 

array([[ 1, -1],
       [ 2, -2]])

 Column vector of constant terms b:

[ 7 14]

 Determinant of matrix: 0.0
The system of linear equations has no solution or infinitely many solutions.


## Ejercicio 3 (no tiene solución)

In [75]:
########################### Exercise 3
print('\n ------------- Exercise 3 ------------- \n')

augmented_A = sp.Matrix([[1, -1, 7],[2, -2, 10]])

print('The augmented matrix (A|b):')
pprint(augmented_A)
A_new = augmented_A.rref()[0]
print('The row echelon form of the matrix is:')
pprint(A_new)

A = np.array([[1, -1], [2, -2]])
print('\n Coefficient matrix A: \n')
pprint(A)

print('\n Column vector of constant terms b:\n')
b = np.array([7, 14])
print(b)

detA = np.linalg.det(A)
print('\n Determinant of matrix:', detA)

if detA == 0:
    print("The system of linear equations has no solution or infinitely many solutions.")
else: 
    print("The system of linear equations has exactly one solution:")
    u = np.linalg.solve(A,b)
    print(u)



 ------------- Exercise 3 ------------- 

The augmented matrix (A|b):
Matrix([
[1, -1,  7],
[2, -2, 10]])
The row echelon form of the matrix is:
Matrix([
[1, -1, 0],
[0,  0, 1]])

 Coefficient matrix A: 

array([[ 1, -1],
       [ 2, -2]])

 Column vector of constant terms b:

[ 7 14]

 Determinant of matrix: 0.0
The system of linear equations has no solution or infinitely many solutions.


# Otros ejercicios

In [76]:
C = np.arange(16)
print(C)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [77]:
C.shape = (4,4)  # reordena el arreglo anterior a un arreglo de 4x4
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [78]:
print('Primera fila', C[0])

Primera fila [0 1 2 3]


In [79]:
print('Última fila', C[-1])

Última fila [12 13 14 15]


In [80]:
E = np.zeros((8,8))
E

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [81]:
for i in range(8):
    E[i][i] = 1
E

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [82]:
F = np.ones((4,5))
print(F)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [83]:
F.astype(int)  
F

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
augmented_F = Matrix(F)
pprint(augmented_F)

Matrix([
[1.0, 1.0, 1.0, 1.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 1.0]])


In [85]:
augmented_F.rref()[0]

Matrix([
[1, 1.0, 1.0, 1.0, 1.0],
[0,   0,   0,   0,   0],
[0,   0,   0,   0,   0],
[0,   0,   0,   0,   0]])